version: '3'

services:
  service:
    image: nlepage/grpc-hellow:service
    build: service
  go:
    image: nlepage/grpc-hellow:go
    build: go/hellow
    command: server
    depends_on:
      - service
  node:
    image: nlepage/grpc-hellow:node
    build: node
    command: server
    depends_on:
      - service
